all:
  children:
    k8s_cluster:
      children:
        control_plane:
          hosts:
            STG-Hazegh-VM1.DC.SNAPPCLOUD.IO:
              ansible_host: 10.160.1.22
        workers:
          hosts:
            STG-Hazegh-VM2.DC.SNAPPCLOUD.IO:
              ansible_host: 10.160.1.28
            STG-Hazegh-VM3.DC.SNAPPCLOUD.IO:
              ansible_host: 10.160.1.29

